export const RECORDER = {
  START_RECORDING: "recorder/START_RECORDING",
  STOP_RECORDING: "recorder/STOP_RECORDING",
  CLEAR_RECORING: "recorder/CLEAR_RECORDING",
  PLAY_RECORDING: "recorder/PLAY_RECORDING",
  RECORD_ACTION: "recorder/RECORD_ACTION",
  PLAY_NEXT_ACTION: "recorder/PLAY_NEXT_ACTION"
};
